### ISSUE TITLE
[2016.11.8] Centos6 Tests are hanging during test runs

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#505]
It hangs on this test with the stacktrace:

```
17:49:41 [CPU:100.0%|MEM:39.0%|Z:0] Test a large number of events, one at a time ... FAIL (7.380s)
17:49:41   test_event_many_backlog (unit.utils.event_test.TestSaltEvent)
17:49:43 17:49:38,835 [tornado.application                                       :611 ][ERROR   ] Exception in callback (<moto.packages.httpretty.core.socket object at 0x1a40c890>, <function null_wrapper at 0x1bc98140>)
17:49:43 Traceback (most recent call last):
17:49:43   File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 865, in start
17:49:43     handler_func(fd_obj, events)
17:49:43   File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
17:49:43     return fn(*args, **kwargs)
17:49:43   File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 246, in accept_handler
17:49:43     connection, address = sock.accept()
17:49:43   File "/usr/lib64/python2.6/socket.py", line 198, in accept
17:49:43     return _socketobject(_sock=sock), addr
17:49:43 TypeError: __init__() got an unexpected keyword argument '_sock'
17:49:43 17:49:38,839 [tornado.application                                       :611 ][ERROR   ] Exception in callback (<moto.packages.httpretty.core.socket object at 0x17067b50>, <function null_wrapper at 0x1bc98398>)
17:49:43 Traceback (most recent call last):
17:49:43   File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 865, in start
17:49:43     handler_func(fd_obj, events)
17:49:43   File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
17:49:43     return fn(*args, **kwargs)
17:49:43   File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 246, in accept_handler
17:49:43     connection, address = sock.accept()
17:49:43   File "/usr/lib64/python2.6/socket.py", line 198, in accept
17:49:43     return _socketobject(_sock=sock), addr
17:49:43 TypeError: __init__() got an unexpected keyword argument '_sock'
```

**Comment by Ch3LL** [comment]
update: haven't been able to replicate it. Trying to run the entire unit test suite to see if i can. I can't quit seem to figure out why we would be getting an unexpected keyword argument here because I checked the code and _socketobject does indeed expect `_sock` as a legitimate kwarg.

**Comment by Ch3LL** [comment]
k finally replicated the issue creating a vm with dev builder in jenkins and running: `python tests/runtests.py -v -u` diving in more now

**Comment by Ch3LL** [comment]
verified it works on v2016.11.7...runnign git bisect

**Comment by Ch3LL** [comment]
60b406e088e327a19d98b9e537f3d52b51722fa2 which is from this PR:

https://github.com/saltstack/salt/pull/42959

```
60b406e088e327a19d98b9e537f3d52b51722fa2 is the first bad commit
commit 60b406e088e327a19d98b9e537f3d52b51722fa2
Author: rallytime <nicole@saltstack.com>
Date:   Thu Aug 10 17:15:45 2017 -0400

    @mock_elb needs to be changed to @mock_elb_deprecated as well

:040000 040000 d300132210d889d3133f3c44d28ef66c95c7da2a 92cdfdde43e44828c909b6366fe586316466a384 M      tests
```
