### ISSUE TITLE
Failed test: unit.modules.test_virtualenv.VirtualenvTestCase.test_get_virtualenv_version_from_shell

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#625]
- unit.modules.test_virtualenv.VirtualenvTestCase.test_get_virtualenv_version_from_shell
```
Traceback (most recent call last):
  File "/testing/salt/modules/virtualenv_mod.py", line 155, in create
    import virtualenv
  File "//testing/tests/support/helpers.py", line 445, in __fake_import__
    'Forced ImportError raised for {0!r}'.format(name)
ImportError: Forced ImportError raised for 'virtualenv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_virtualenv.py", line 229, in test_get_virtualenv_version_from_shell
    '/tmp/foo',
  File "/usr/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/testing/salt/modules/virtualenv_mod.py", line 170, in create
    'Returned data: {1}'.format(version_cmd, ret)
  File "/testing/salt/exceptions.py", line 122, in __init__
    import salt.utils.stringutils
  File "//testing/tests/support/helpers.py", line 457, in __fake_import__
    return self.__original_import(name, globals_, locals_, fromlist, level)
TypeError: __fake_import__() missing 3 required positional arguments: 'globals_', 'locals_', and 'fromlist'
```
This is on Python 3.

**Comment by terminalmage** [comment]
@garethgreenaway This is fixed along with a bunch of the other PY3 failures in https://github.com/saltstack/salt/pull/45038 (I tacked on a bunch of fixes unrelated to docker while I was looking into the PY3 docker failures).
