### ISSUE TITLE
[2018.3] User test failing 

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1021]
- integration.states.test_user.UserTest.test_user_if_present

```
Traceback (most recent call last):
  File "/testing/tests/support/mixins.py", line 550, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib/python3.5/unittest/case.py", line 677, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/integration/states/test_user.py", line 59, in test_user_if_present
    self.assertSaltTrueReturn(ret)
  File "/testing/tests/support/mixins.py", line 556, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
An exception occurred in this state: Traceback (most recent call last):
  File "/testing/salt/state.py", line 1913, in call
    **cdata['kwargs'])
  File "/testing/salt/loader.py", line 1834, in wrapper
    return f(*args, **kwargs)
  File "/testing/salt/states/user.py", line 613, in present
    __salt__['file.mkdir'](val, pre['uid'], pre['gid'], 0o755)
  File "/testing/salt/modules/file.py", line 5554, in mkdir
    makedirs_perms(directory, user, group, mode)
  File "/testing/salt/modules/file.py", line 5659, in makedirs_perms
    int('{0}'.format(mode)) if mode else None)
  File "/testing/salt/modules/file.py", line 4590, in check_perms
    ret['comment'].append(
AttributeError: 'str' object has no attribute 'append'
```

**Comment by rallytime** [comment]
This was caused by https://github.com/saltstack/salt/pull/48398

**Comment by rallytime** [comment]
This is fixed with https://github.com/saltstack/salt/pull/48508
